name: 'PROS Build'
description: 'Automatically build PROS templates'
branding:
  color: 'blue'
  icon: 'box'
  colorized: true

inputs:
  multithreading:
    required: false
    default: true
    description: Whether to use multithreading when building the project (-j flag in make)
  no_commit_hash:
    required: false
    default: false
    description: Whether to not include the commit hash in the artifact name
runs:
  using: 'Docker'
  image: 'docker://ghcr.io/abucky0/pros-build:main'