name: Pros Build
description: Automatically build pros projects

inputs:
  repository:
    description: Target repository
    required: false
    default: ${{ github.repository }}
  upload-built-template:
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        path: ./pros-project
    - run: cp -r ./pros-project/* ./ # its incredibly silly that I have to do this but otherwise it interferes with other checkouts
      shell: bash

    - name: Check if template
      id: template
      run: |
        template=$(awk -F'=' '/^IS_LIBRARY:=/{print $2}' Makefile)
        echo $template
        echo "template=$template" >> $GITHUB_OUTPUT
      env:
        TEMPLATE: ${{ steps.template.outputs.template }}
      shell: bash

    - name: Get short SHA
      if: ${{ steps.template.outputs.template == 1 && inputs.upload-built-template}}
      id: short-sha
      shell: bash
      run: |
        if [ $ACTION = opened ]; then
            # we have to get the head sha directly from the pr api, because github silly ig
            echo "then"
            sha=$(wget -O- --quiet https://api.github.com/repos/LemLib/LemLib/pulls/$PR_NUM | jq -r .head.sha | head -c 6)
        else
            echo "else"
            sha=$(echo "$AFTER" | head -c 6)
        fi
        echo "sha=$sha" >> $GITHUB_OUTPUT
      env:
        AFTER: ${{ github.event.after }} # this isn't present for pr opened events
        ACTION: ${{github.event.action}}
        PR_NUM: ${{github.event.number}}
        SHA: ${{ steps.short-sha.outputs.sha }}

    - name: Get version number
      if: ${{ steps.template.outputs.template == 1 && inputs.upload-built-template}}
      id: version
      shell: bash
      run: |
        version=$(awk -F'=' '/^VERSION:=/{print $2}' Makefile)
        echo "version=$version" >> "$GITHUB_OUTPUT"
      env:
        VER: ${{ steps.version.outputs.version }}

    - name: Get Template Postfix
      if: ${{ steps.template.outputs.template == 1 && inputs.upload-built-template}}
      id: template-postfix
      shell: bash
      run: |
        echo postfix="$VER+$SHA" >> "$GITHUB_OUTPUT"
      env:
        POSTFIX: ${{ steps.template-postfix.outputs.postfix }}

    - name: Get Template Name
      if: ${{ steps.template.outputs.template == 1 && inputs.upload-built-template}}
      id: template-name
      shell: bash
      run: |
        echo name=$TEMPLATE_NAME@$POSTFIX >> "$GITHUB_OUTPUT"
      env:
        POSTFIX: ${{ steps.template-postfix.outputs.postfix }}
        TEMPLATE_NAME: ${{ github.event.repository.name }}

    - name: Update version in Makefile
      if: ${{ steps.template.outputs.template == 1 && inputs.upload-built-template}}
      shell: bash
      run: sed -i "s/^VERSION:=.*\$/VERSION:=$POSTFIX/" Makefile
      env:
        POSTFIX: ${{ steps.template-postfix.outputs.postfix }}

    #- name: Install ARM Toolchain
    #uses: fiam/arm-none-eabi-gcc@v1
    #with:
    #release: "10-2020-q4"

    #- name: Setup Python
    #uses: actions/setup-python@v2
    #with:
    #python-version: 3.9

    #- name: PIP Installer
    #uses: BSFishy/pip-action@v1
    #with:
    #packages: pros-cli

    #- name: Testing PROS Install
    #run: pros --version
    #shell: bash

    #- name: Checkout
    #uses: actions/checkout@v4
    #with:
    #repository: ${{ inputs.repository }}
    #path: ./pros-project

    #- name: Build PROS Project
    #run: |
    #make clean quick -j
    #shell: bash
