name: 'PROS Build'
description: 'Automatically build PROS templates'
branding:
  color: 'blue'
  icon: 'box'
  colorized: true

inputs:
  multithreading:
    required: false
    default: true
    description: Whether to use multithreading or not
runs:
  using: 'Docker'
  image: 'Dockerfile'