name: Pros Build
description: Automatically build pros projects

inputs:
  project: 
    description: 'Project to build'
    required: false
  repository:
    description: 'Target repository'
    required: false
    default: ${{ github.repository }}

runs:
  using: composite
  shell: bash
  steps:
    - name: Install ARM Toolchain
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: "10-2020-q4"

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: PIP Installer
      uses: BSFishy/pip-action@v1
      with:
        packages: pros-cli

    - name: Testing PROS Install
      run: pros --version

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'Lemlib/LemLib'

    - name: Build PROS Project
      run: make clean quick -j
