name: 'ABUCKY0 PROS Build'
description: 'Build a PROS Project'
branding:
  color: 'blue'
  icon: 'box'
  colorized: true

inputs:
  repository:
    description: Target repository
    required: false
    default: ${{ github.repository }}
  library_path:
    required: false
    default: null
    description: The path of the library inside of the `include` directory. Specifying a value for this input will cause the action to upload the built library in template form as an artifact.
  after:
    required: false
    default: ${{ github.event.after }}
    description: The commit hash to checkout
  action:
    required: false
    default: ${{ github.event.action }}
    description: The action that triggered the workflow
  pr_num:
    required: false
    default: ${{ github.event.number }}
    description: The PR number
  multithreading:
    required: false
    default: false
    description: Whether to use multithreading or not
runs:
  using: 'Docker'
  image: 'Dockerfile'
  env:
    AFTER: ${{ inputs.after }} # this isn't present for pr opened events
    ACTION: ${{ inputs.action }}
    PR_NUM: ${{ inputs.pr_num }}
    LIBRARY_PATH: ${{ inputs.library_path }}
    REPOSITORY: ${{ inputs.repository }}