name: Pros Build
description: Automatically build pros projects

inputs:
  repository:
    description: Target repository
    required: false
    default: ${{ github.repository }}
  upload-built-template:
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        path: ./pros-project
    - run: cp -r ./pros-project/* ./

    - name: Check if template
      id: template
      run: |
        template=$(awk -F'=' '/^IS_LIBRARY:=/{print $2}' Makefile)
        echo "template=$template" >> $GITHUB_OUTPUT
        echo template
      env:
        TEMPLATE: ${{ steps.template.outputs.template }}
      shell: bash

    - name: Get short SHA
      if: ${{ env.TEMPLATE == 1 && inputs.upload-built-template}}
      id: short-sha
      shell: bash
      run: |
        if [ ${{ github.event.action }} = opened ]; then
            # we have to get the head sha directly from the pr api, because github silly ig
            echo "then"
            sha=$(wget -O- --quiet https://api.github.com/repos/LemLib/LemLib/pulls/${{ github.event.number }} | jq -r .head.sha | head -c 6)
        else
            echo "else"
            sha=$(echo ${{ github.event.after }} | head -c 6)
        fi
        echo "sha=$sha" >> $GITHUB_OUTPUT
      env:
        SHA: ${{ steps.short-sha.outputs.sha }}

    #- name: Install ARM Toolchain
    #uses: fiam/arm-none-eabi-gcc@v1
    #with:
    #release: "10-2020-q4"

    #- name: Setup Python
    #uses: actions/setup-python@v2
    #with:
    #python-version: 3.9

    #- name: PIP Installer
    #uses: BSFishy/pip-action@v1
    #with:
    #packages: pros-cli

    #- name: Testing PROS Install
    #run: pros --version
    #shell: bash

    #- name: Checkout
    #uses: actions/checkout@v4
    #with:
    #repository: ${{ inputs.repository }}
    #path: ./pros-project

    #- name: Build PROS Project
    #run: |
    #make clean quick -j
    #shell: bash
