name: PROS Build Example
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run abucky0/pros-build
        uses: abucky0/pros-build@v1.0.0
        with:
          library_path: ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name:  build-artifact
          path:  ${{ github.workspace }}/template/*