name: PROS Build Example

on:
    push:
    pull_request:
      branches: "**"
  
    workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run PROS-build
        id: test
        uses: LemLib/pros-build
        with:
          multithreading: true
          no_commit_hash: false

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name:  ${{ steps.test.outputs.name }}
          path:  ${{ github.workspace }}/template/*

      - name: Add Artifact to Job Summary
        run: 'echo "### 📦 Artifact url: ${{ steps.upload.outputs.artifact-url}}" >> $GITHUB_STEP_SUMMARY'
  