name: PROS Build Example
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run abucky0/pros-build
        id: test
        uses: abucky0/pros-build@v1.0.0-alpha
        with:
          library_path: ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name:  ${{ steps.test.outputs.name }}
          path:  ${{ github.workspace }}/template/*