name: Tests
on:
    push:
    pull_request:
      branches: "**"


jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
          id-token: write
        env:
          REPO_LOWER: ${{ github.repository_owner }}/${{ github.repository }}
      
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

          - name: Build Image
            id: build
            uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
            with:
                context: .
                push: false
                tags:  ${{ env.REPO_LOWER }}:${{ github.sha }}
                cache-from: type=gha,type=local,src=/tmp/.buildx-cache
                cache-to: type=gha,type=local,dest=/tmp/.buildx-cache
            
          - name: Save Image
            run: docker save ${{ env.REPO_LOWER }}:${{ github.sha }} > image.tar

          - name: upload-artifact
            uses: actions/upload-artifact@v4
            with:
              name: image
              path: image.tar
    
    # ----------------------------------------
    # RUN TESTS
    # ----------------------------------------
    Test_LemLib:
        name: "Test LemLib (And Upload Artifacts)"
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout LemLib
              uses: actions/checkout@v4
              with:
                repository: LemLib/LemLib
                ref: stable
            - name: Load Image
              uses: actions/download-artifact@v4
              with:
                name: image
                
            - name: Checkout
              uses: actions/checkout@v4
              with:
                path: ./action/
            
            - name: Edit Action.yml File to point to local image
              run: |
                sed -i 's@image: "docker://ghcr.io/abucky0/pros-build:main"@image: "docker-archive://image.tar"@g' ./action/action.yml
            
            - name: Run PROS-build
              id: test
              uses: ./action
              with:
                multithreading: true
                no_commit_hash: false
            
            - name: Upload Artifact
              id: upload
              uses: actions/upload-artifact@v4
              with:
                name:  ${{ steps.test.outputs.name }}
                path:  ${{ github.workspace }}/template/*
            
            - name: Add Artifact to Job Summary
              run: 'echo "### 📦 Artifact url: ${{ steps.upload.outputs.artifact-url}}" >> $GITHUB_STEP_SUMMARY'