name: Tests
on:
    push:
    pull_request:
      branches: "**"


jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
          id-token: write
      
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

          - name: Build Image
            id: build
            uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
            with:
                context: .
                push: false
                load: true
                tags:  abucky0:action
                cache-from: type=gha
                cache-to: type=gha,mode=max
            
          - name: Save Image
            run: docker save abucky0:action > image.tar

          - name: upload-artifact
            uses: actions/upload-artifact@v4
            with:
              name: image
              path: image.tar
    
    # ----------------------------------------
    # RUN TESTS
    # ----------------------------------------
    Test_LemLib:
        name: "Test LemLib (And Upload Artifacts)"
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout LemLib
              uses: actions/checkout@v4
              with:
                repository: LemLib/LemLib
                ref: stable

            - name: Download Image
              uses: actions/download-artifact@v4
              with:
                name: image.tar
            
            - name: Load Image
              run: docker load < image.tar

            - name: Checkout
              uses: actions/checkout@v4
              with:
                path: ./action/
            
            - name: Edit Action.yml File to point to local image
            # image: 'docker://ghcr.io/abucky0/pros-build:main'
            # replaced with image from Load Image Step
              run: |
                cat ./action/action.yml
                sed -i 's/docker:\/\/ghcr.io\/abucky0\/pros-build:main/docker:\/\/abucky0:action/g' ./action/action.yml
                cat ./action/action.yml
            
            - name: Run PROS-build
              id: test
              uses: ./action
              with:
                multithreading: true
                no_commit_hash: false
            
            - name: Upload Artifact
              id: upload
              uses: actions/upload-artifact@v4
              with:
                name:  ${{ steps.test.outputs.name }}
                path:  ${{ github.workspace }}/template/*
            
            - name: Add Artifact to Job Summary
              run: 'echo "### 📦 Artifact url: ${{ steps.upload.outputs.artifact-url}}" >> $GITHUB_STEP_SUMMARY'