name: Test EZ Template
on:
  workflow_call:

env:
  GH_PR_NUM: ${{ github.event.inputs.GITHUB_PR_NUM }}
  GH_EVENT_NAME: ${{ github.event.inputs.GH_EVENT_NAME }}

jobs:
  Test_EZ_Template:
    name: "Testing EZ-Template"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: EZ-Robotics/EZ-Template
          ref: v3.0.1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./action/

      - name: Test With Upload + Bonus Files
        id: test
        uses: ./action/

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.test.outputs.name }}
          path: "template/*"

      - name: Add Artifact to Job Summary
        run: 'echo "### 📦 Artifact url: ${{ steps.upload.outputs.artifact-url}}" >> $GITHUB_STEP_SUMMARY'
