name: Test LemLib
on:
  workflow_call:
    inputs:
      GH_PR_NUM:
        description: "The PR number"
        required: true
        type: string

env:
  GH_PR_NUM: ${{ secrets.GH_PR_NUM }}
jobs:
  Test_LemLib:
    name: "Testing LemLib"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: LemLib/LemLib
          ref: stable

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./action/

      - name: Test With Upload
        id: test
        uses: ./action/

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.test.outputs.name }}
          path: "template/*"

      - name: Add Artifact to Job Summary
        run: 'echo "### 📦 Artifact url: ${{ steps.upload.outputs.artifact-url}}" >> $GITHUB_STEP_SUMMARY'
