name: Test EZ Template
on:
  workflow_call:
    inputs:
      GH_PR_NUM:
        description: "The PR number"
        required: true
        type: string

env:
    GH_PR_NUM: ${{ inputs.GH_PR_NUM }}
jobs:
  Test_EZ_Template:
    name: "Testing EZ-Template"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: EZ-Robotics/EZ-Template
          ref: v3.0.1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./action/

      - name: Test With Upload (EZ-Template)
        id: test
        uses: ./action/
        env:
            GH_PR_NUM: ${{ inputs.GH_PR_NUM }}

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.test.outputs.name }}
          path: "template/*"

      - name: Add Artifact to Job Summary
        run: 'echo "### 📦 Artifact url: ${{ steps.upload.outputs.artifact-url}}" >> $GITHUB_STEP_SUMMARY'
