name: Test action
on:
  push:
    paths-ignore:
      - .gitignore
      - README*.md
      - LICENSE
      - .github/**
      - "!.github/workflows/test.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-lemlib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: LemLib/LemLib
          ref: 6fc0838e0aa1de03d7864002888f5d874b691910

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./action/

      - name: Test With Upload + Bonus Files
        uses: ./action/
        with:
          library-path: lemlib

  test-lemlib-without-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: LemLib/LemLib
          ref: 6fc0838e0aa1de03d7864002888f5d874b691910

      - name: Check If Template
        id: template
        run: |
          template=$(awk -F'=' '/^IS_LIBRARY:=/{print $2}' Makefile)
          echo $template
          echo "template=$template" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./action/

      - name: Test With Upload + Bonus Files
        uses: ./action/
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name:  ${{ steps.template.outputs.template }}
          path: "template/*"

  test-ez:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: EZ-Robotics/EZ-Template
          ref: v3.0.1

      - name: Check If Template
        id: template
        run: |
          template=$(awk -F'=' '/^IS_LIBRARY:=/{print $2}' Makefile)
          echo $template
          echo "template=$template" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./action/

      - name: Test With Upload + Bonus Files
        uses: ./action/
        with:
          library-path: EZ-Template
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name:  ${{ steps.template.outputs.template }}
          path: "template/*"
