name: Test LemLib without Uploading an Artifact
on:
    workflow_call:
        inputs:
            GH_PR_NUM:
                description: "The PR number"
                required: true
                type: string
            CALLER_TOKEN:
                description: "The token of the caller"
                required: true
                type: string
env:
    GH_PR_NUM: ${{ inputs.GH_PR_NUM }}

jobs:
  Test_LemLib_Without_Uploading_an_Artifact:
    name: "Testing LemLib Without Uploading an Artifact"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: LemLib/LemLib
          ref: 6fc0838e0aa1de03d7864002888f5d874b691910

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./action/
          
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: image.tar
          github-token: ${{ inputs.CALLER_TOKEN }}

      - name: Load Image
        id: load
        run: |
         echo "tag=$(docker load -i ./image.tar | grep -oP 'Loaded image: \K.*')" > $GITHUB_OUTPUT

      - name: Edit Action.yml With Local Image
        run: |
          cat action/action.yml
          sed -i 's|docker://ghcr.io/abucky0/pros-build:main|docker://${{steps.load.outputs.tag}}|g' action/action.yml
          cat action/action.yml
      
      - name: Test Without Upload
        uses: ./action/
        env:
            GH_PR_NUM: ${{ inputs.GH_PR_NUM }}
