name: Test action
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - README*.md
      - LICENSE
      - .github/**
      - "!.github/workflows/test.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: LemLib/LemLib
          ref: 6fc0838e0aa1de03d7864002888f5d874b691910

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./action/

      - name: test
        uses: ./action/
        with:
          library-name: LemLib
