name: Test LemLib
on:
  workflow_call:
    inputs:
      GITHUB_PR_NUM:
        description: "The PR number"
        required: true
        type: number
      GH_EVENT_NAME:
        description: "The event name"
        required: true
        type: string
env:
  GH_PR_NUM: ${{ github.event.inputs.GITHUB_PR_NUM }}
  GH_EVENT_NAME: ${{ github.event.inputs.GH_EVENT_NAME }}

jobs:
  Test_LemLib:
    name: "Testing LemLib"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: LemLib/LemLib
          ref: stable

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./action/

      - name: Test With Upload
        id: test
        uses: ./action/
        env:
          GH_PR_NUM: ${{ env.GH_PR_NUM }}
          GH_EVENT_NAME: ${{ env.GH_EVENT_NAME }}

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.test.outputs.name }}
          path: "template/*"

      - name: Add Artifact to Job Summary
        run: 'echo "### 📦 Artifact url: ${{ steps.upload.outputs.artifact-url}}" >> $GITHUB_STEP_SUMMARY'
